@startuml

package controller {
    class CoverController implements Observateur {
            - TextField title
            - DatePicker startDatePicker
            - DatePicker endDatePicker
            - TextField author
            - TextArea participants
            - Label pageNumber
            - ImageView leftArrow
            - ImageView rightArrow
            - ImageView newCarnet
            - ImageView loadCarnet
            - VBox background
            - Stage stage
            - Carnet carnet
            --
            + CoverController(Stage stage, Carnet carnet)
            + void initialize()
            + void turnPageRight()
            + void setMinDate()
            + void setMaxDate()
            + void load()
            + void createNew()
            + void reagir()
            - void savePage()
            - short verifyCarnet()
            - void loadCarnet()
            - void export()
            - void switchScenes()
    }

    class DayPageController implements Observateur {
            - TextField title
            - TextArea description
            - Button imgButton
            - Rectangle photo
            - Label pageNumber
            - ImageView leftArrow
            - ImageView rightArrow
            - Slider emotions
            - ImageView home
            - ImageView export
            - VBox background
            - Stage stage
            - Carnet carnet
            --
            + DayPageController(Stage stage, Carnet carnet)
            + void initialize() throws FileNotFoundException
            + void openImage()
            + void checkArrows()
            + void turnPageLeft()
            + void turnPageRight()
            + void goToCover()
            + void export()
            + void reagir()
            - void savePage()
            - void switchScenes()
            - void setPhoto(String photoURL)
            - void setArrows()
    }

    interface Observateur {
        + void reagir()
    }
}

package carnet {
    class Cover extends Page {
            - String title
            - String startDate
            - String endDate
            - String author
            - String participants
            --
            + Cover()
            + String getAuthor()
            + void setAuthor(String author)
            + String getParticipants()
            + void setParticipants(String participants)
            + String getTitle()
            + void setTitle(String title)
            + LocalDate getStartDate()
            + void setStartDate(LocalDate startDate)
            + LocalDate getEndDate()
            + void setEndDate(LocalDate endDate)
            + void emptyStartDate()
            + void emptyEndDate()
            + boolean equals(Object o)
    }

    abstract class Page {
            - final int nbPage
            --
            + Page(int nbPage)
            + int getNbPage()
    }

    class SujetObserve {
            - transient final ArrayList<Observateur> observers
            --
            + SujetObserve()
            + void addObserver(Observateur o)
            + void notifyObservers()
    }

    class Carnet extends SujetObserve {
            - final Cover cover
            - ArrayList<DayPage> pages
            - int currentPage
            - Carnet savedCarnetImage
            --
            + Carnet()
            + void nextPage()
            + void previousPage()
            + void createPage()
            + void setCurrentPage(int page)
            + int getCurrentPageNb()
            + int getNbPages()
            + DayPage getCurrentPage()
            + Cover getCover()
            + ArrayList<DayPage> getPages()
            + boolean isNew()
            + boolean isSaved()
            + void saveCarnetImage()
            + void copyCarnet(Carnet carnet)
            + void export(String filePath)
            + void importCarnet(String filePath)
            + boolean equals(Object obj)
            + String toString()
    }

    class DayPage extends Page {
            - String title
            - String text
            - String photo
            - int emotions
            --
            + static final DayPage newPage
            --
            + DayPage(int nbPage)
            + void setPhoto(String photo)
            + void setTitle(String title)
            + void setText(String text)
            + String getTitle()
            + String getText()
            + String getPhoto()
            + int getEmotions()
            + void setEmotions(int emotions)
            + boolean equals(DayPage p)
    }
}

package outils {
    class DateChecker {
            - DateChecker()
            --
            + static void setBeginDateBounds(DatePicker begin_date, LocalDate end_date)
            + static void setEndDateBounds(DatePicker end_date, LocalDate begin_date)
    }

    class FontResizer {
        -FontResizer()
        --
        +static void adjustFontSize(TextField, double, double)
        +static double calculateFontSize(String, double, double, double)
    }
}

class Main extends Application {
    --
    + void start(Stage stage)
}

controller.CoverController --"1" carnet.Cover
controller.CoverController --"1" carnet.Carnet
controller.DayPageController --"1" carnet.Carnet
controller.DayPageController --"*" carnet.DayPage
carnet.Carnet --o carnet.Page
carnet.SujetObserve --"*" controller.Observateur


@enduml